### ISSUE TITLE
When moving the highlighting moves extra step(s) in the moved direction with separators.

### ISSUE THREAD

**Issue by sq5pgj** [mate-desktop/mozo#16]
I inserted two separators to the menu and then highlighted one of the items and pushed the move up button.
The selected item has been moved but it become no longer highlighted.
It becomes even more frustrating when you have two separators and want to move up the last item on the list.
In case of menus without separators it looks like to be correct.

**Comment by infirit** [comment]
I have no problem adding separators and moving things around. Can you be more specific and list every step and where you are having problems.

**Comment by sq5pgj** [comment]
As the screen are not visible here, I will list the menu I tried to edit:
The menu has 15 items:
hgview,
Meld,
QtCreator,
Separator,
Qt4Assistant, 
Qt4Designer, 
Qt4Ling, 
Qt4Demo, 
Separator,
Qt5Designer, 
Qt5 Assistant,
Qt5Ling,
Separator,
RapidSVN,
regexxer.

I highlighted the last item,the regexer and pushed button 'move up'.
Then the regexer went above the RapidSVN (that was expected), but now the highlighted item is no longer the regexxer. Now Qt5Assistant is highlighted. (that was on screen2). And this is incorrect, unexpected and confusing.
So I clicked the regexxer item - it becomes highlighted again (on screen3) and pushed the button move up. And again, the regexer jumped above the separator (that is correct), but again,   Qt5Assistant became highlighted (again incorrect: unexpected and confusing).

**Comment by ztm** [comment]
Same problem here. Inserting separators and then pressing MOVE UP/DOWN the highlighted item moves up/down but after moving, another item (depends on the number of inserted separators) gets highlighted. So moving an item with inserted separators item must be selected before every move. With no separators you just have to press the direction buttons.
Another problem is that reordering the items has absolutely no effect on the Mint Menu which was my main goal for groupping my apps.

**Comment by infirit** [comment]
Confirmed and updated the issue description a bit.

> Another problem is that reordering the items has absolutely no effect on the Mint Menu which was my main goal for groupping my apps.

You'll need to ask the mintmenu folk to take into account the menu file that is created which overrides the default. The file is ``~/.config/menu/mate-applications.menu``

**Comment by monsta** [comment]
Please try https://github.com/mate-desktop/mozo/pull/20 - it should fix the problem.
