### ISSUE TITLE
editing entry in menu prevents the application from being an option for "Preferred Applications"

### ISSUE THREAD

**Issue by KermitBRickman** [mate-desktop/mozo#18]
I installed Banshee and want to set it as my preferred multimedia player. I edited the entry in the menu, adding the "--hide" option so that Banshee will open to the tray, but after editing the menu item, Banshee no longer appears as an option in "Preferred Applications". In fact, even if the user simply opens the properties window for a menu item without making any changes, that application no longer gets listed as an option in "Preferred Applications" ...

Steps to reproduce:
1) install banshee
2) open "Preferred Applications" and navigate to the "Multimedia" tab ... "Banshee Media Player" should be listed as an option for "Multimedia Player" at this point.
3) Close "Preferred Applications"
4) Open the menu editor
5) Open the properties window for the "Banshee" menu item
6) Close the properties window. Close the menu editor.
7) Open "Preferred Applications" and navigate to the "Multimedia" tab
8) Banshee is no longer listed as an option for "Multimedia Player"

This worked correctly in Fedora 20.

**Comment by infirit** [comment]
There appears to be a problem when desktop files are in ```~/.local/share/applications```.

**Comment by monsta** [comment]
> In fact, even if the user simply opens the properties window for a menu item without making any changes, that application no longer gets listed as an option in "Preferred Applications" ...

That's where the bug https://github.com/mate-desktop/mozo/issues/17 comes in to assist this one :smile:

**Comment by monsta** [comment]
Let's move to https://github.com/mate-desktop/mate-control-center/issues/150. Mozo's fault is only https://github.com/mate-desktop/mozo/issues/17.
