### ISSUE TITLE
Showing added Menu fails with not found warning in MainWindow.py:80

### ISSUE THREAD

**Issue by kdicke** [mate-desktop/mozo#24]
In a newly installed ubuntu-mate 15.04 (mate 1.8.2) mozo fails to add a new menu item to the Applications menu. The warning given is:
/usr/lib/python2.7/dist-packages/Mozo/MainWindow.py:80: Warning: Source ID 34 was not found when attempting to remove it
  gobject.source_remove(self.timer)

To reproduce: 
 1) install ubuntu-mate 15.04
 2) select: System->Preferences->Look and Feel->Main Menu
   invokes mozo and brings up Main Menu editor.
 3) click on New Menu button
   brings up Directory Properties dialog
 4) set Name: to "myNewMenu" and click on OK
    myNewMenu appears as an Item under Applications but the show button is not checked
 5) check show button for myNewMenu
 6) click on Close button
    myNewMenu is not shown in Applications menu
 7) repeat step 2) above
   myNewMenu appears as an Item under Applications but the show button is not checked
 8) repeat steps 4) through 8) and you never get the menu shown.

Trace and error files are captured using "python -m trace --trace /usr/bin/mozo"

[mojo.stderr.txt](https://github.com/mate-desktop/mozo/files/40289/mojo.stderr.txt)
[mojo.stderr2.txt](https://github.com/mate-desktop/mozo/files/40292/mojo.stderr2.txt)
[mojo.trace.txt](https://github.com/mate-desktop/mozo/files/40291/mojo.trace.txt)
[mojo.trace2.txt](https://github.com/mate-desktop/mozo/files/40290/mojo.trace2.txt)

**Comment by monsta** [comment]
This should be fixed by now
