### ISSUE TITLE
Unable to delete any entry via Mozo

### ISSUE THREAD

**Issue by Kallestofeles** [mate-desktop/mozo#33]
Hi,

Unable to delete any main menu entry via Mozo.
Upon selecting an item and clicking delete on the right-hand menu (or via right-click and selecting delete) nothing happens, not even logs in terminal output.

OS: Arch Linux (up to date) with full mate and mate-extra package collections
Mozo version: mozo 1.18.0-1

**Comment by thatismypickedusername** [comment]
Same happened on my computer: Debian jessie, Mate 1.8 , mozo 1.8.0-2

**Comment by vkareh** [comment]
This seems fixed now
