### ISSUE TITLE
We cannot to see movoment of items in mozo window.

### ISSUE THREAD

**Issue by inoueta** [mate-desktop/mozo#36]
#### Expected behaviour
When we move items, we can see the movement immediately in mozo window.

#### Actual behaviour
We cannot see item movement  in mozo window.
Moreover, operation seems not done until we close mozo window.

#### Steps to reproduce the behaviour
Start mozo.  Select one item. Push "Move Up" or "Move Down" button.

#### MATE general version
Mate 1.18.0

#### Package version
mozo 1.18.0
But, I know this bug exist from 1.12.1 or before.

#### Linux Distribution
FreeBSD 11.1 Release

**Comment by vkareh** [comment]
This seems fixed now
