### ISSUE TITLE
Mozo 1.21 : python 3.6.6 is "too" old to build mozo.

### ISSUE THREAD

**Issue by FredBezies** [mate-desktop/mozo#44]
I tried to build mozo 1.21 using tarball. In configure step, I got this error:

configure: error: Python interpreter is too old.

See attached screenshot:
![virtualbox_arch - mate desktop_13_07_2018_21_35_29](https://user-images.githubusercontent.com/8571419/42710597-e6ce5d2e-86e4-11e8-9280-39a54b928b7f.png)

#### MATE general version

1.21.0

#### Package version

Mozo: 1.21.0
Python: 3.6.6-1

#### Linux Distribution

Archlinux

**Comment by raveit65** [comment]
see https://github.com/mate-desktop/mozo/pull/39
You need to build mate-menus and mozo from master for python-3.6
Be warned, you need to rebuild other dependencies of mate-menus too.
I suggest to wait for next major MATE release.
