### ISSUE TITLE
Mozo internationalization incorrect for non-utf8 based desktops

### ISSUE THREAD

**Issue by thorfdbg** [mate-desktop/mozo#6]
The mozo menu editor does not display language specific characters (such as german umlauts) correctly if the desktop character set is not UTF-8. Instead, a "smear-character" appears. The menu of the mate desktop itself is rendered correctly, though.

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/mate-desktop/mozo/commit/97c5474bfa5c3a4d9f72dc8cba87d8e9ba79813f
