### ISSUE TITLE
strange behavior when editing the collection directory

### ISSUE THREAD

**Issue by rbuj** [mate-desktop/mozo#74]
#### Expected behaviour

The content of the collection directory is generated at runtime from https://github.com/mate-desktop/mate-menus/pull/86
and the user should not be able to edit the items in this directory.

#### Actual behaviour

If the user disables one of the items in the collection directory, an equal item is added, at most two equal items are listed, one is enabled and the other is not.

If an item in this directory is deleted using the delete button on mozo dialog, It will remove other occurrences from the menu, i.e. copying the desktop file to the folder ~/.local/share/applications/ and setting the property Hidden=true. 

#### Steps to reproduce the behaviour

Enable/disable/delete one of the items in the collection directory.

To add a new item to the collection directory, drag and drop a desktop launcher on mate panel.

#### MATE general version

upstream

**Comment by raveit65** [comment]
Yes, i noted the in original PR of that feature.
